name: dotted_border
description: A flutter package to let users easily add a dashed border around any widget.
version: 1.0.6
homepage: https://github.com/ajilo297/Flutter-Dotted-Border

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: