name: dotted_border
description: A flutter package to let users easily add a dashed border around any widget.
version: 2.0.0+2
homepage: https://github.com/ajilo297/Flutter-Dotted-Border

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: